
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author CrisRodFe
 */
public class ConsultarCuenta extends javax.swing.JDialog {    
    /**
     * Creates new form ConsultarCuenta
     * @param parent
     * @param modal
     */
    public ConsultarCuenta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        cuentaConsultada = new javax.swing.JTextArea();
        Consultar = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        cuentaConsultar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CONSULTAR DATOS DE CUENTA");
        setBackground(new java.awt.Color(255, 255, 255));

        cuentaConsultada.setColumns(20);
        cuentaConsultada.setRows(5);
        jScrollPane1.setViewportView(cuentaConsultada);

        Consultar.setText("Consultar");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });

        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });

        jLabel1.setText("Número de cuenta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cuentaConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Consultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Consultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Limpiar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cuentaConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Limpia las casillas del panel.
     * @param evt 
     */
    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        cuentaConsultada.setText("");
        cuentaConsultar.setText("");
    }//GEN-LAST:event_LimpiarActionPerformed
    /**
     * Devuelve los datos relativos el número de cuenta introducido por teclado.
     * @param evt 
     */
    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        //Cargamos los datos de las cuentas guardados en el archivo
        Serializar sr = new Serializar();
        String archivo = "datosClientes.dat";            
        ArrayList<CuentaBancaria> cuenta =(ArrayList<CuentaBancaria>)sr.leerObjeto(archivo);
        ArrayList<CuentaAhorro> ahorro =(ArrayList<CuentaAhorro>)sr.leerObjeto(archivo);
        ArrayList<CuentaCorrienteEmpresa> empresa =(ArrayList<CuentaCorrienteEmpresa>)sr.leerObjeto(archivo);
        ArrayList<CuentaCorrientePersonal> personal =(ArrayList<CuentaCorrientePersonal>)sr.leerObjeto(archivo);
        boolean existe=false;
        int a=0;
        //Recorremos el array con los datos de las cuentas guardadas        
        for(int i=0;i<cuenta.size();i++){
        //Comprobamos que la cuenta introducida está guardada y registramos su posición.                          
            if(cuenta.get(i).getNumeroCuenta().equals(cuentaConsultar.getText())){
                existe=true;
                a=i;
            }
        }
        //Imprimimos por pantalla los datos de la cuenta introducida por teclado si existe.
        if(existe){
            cuentaConsultada.append("DATOS DEL TITULAR\n"+
                                    "Nombre: "+cuenta.get(a).getTitularCuenta().getNombre()+"\n"+
                                    "Apellidos: "+cuenta.get(a).getTitularCuenta().getApellidos()+"\n"+
                                    "Fecha de Nacimiento: "+cuenta.get(a).getTitularCuenta().getFechaNacimiento()+"\n"+
                                    "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - \n"+
                                    "DATOS DE LA CUENTA\n"+ 
                                    "Tipo de Cuenta: "+cuenta.get(a).getClass().getName()+"\n"+
                                    "Nº de cuenta: "+cuenta.get(a).getNumeroCuenta());
           if(cuenta.get(a).getClass().getName().equals("CuentaAhorro")){            
                    cuentaConsultada.append("Tipo de interés: "+ahorro.get(a).getTipoInteres()+"%"); 
           }
           if(cuenta.get(a).getClass().getName().equals("CuentaCorrienteEmpresa")){
                    cuentaConsultada.append("\nMáximo descubierto: "+empresa.get(a).getMaxDes()+"€"+
                                            "\nComisión por descubierto: "+empresa.get(a).getComDes()+"€"+
                                            "\nInterés por descubierto: "+empresa.get(a).getIntDes()+"%"+
                                            "\nEntidades autorizadas: "+empresa.get(a).getEntidad().toString()+"{código=cantidad}\n");
           }
           if(cuenta.get(a).getClass().getName().equals("CuentaCorrientePersonal")){
                    cuentaConsultada.append("\nComisión de mantenimiento: "+personal.get(a).getComMantenimiento()+"€"+
                                            "\nEntidades autorizadas: "+personal.get(a).getEntidad().toString()+"{código=cantidad}\n");
           }
        cuentaConsultada.setEditable(false);
        cuentaConsultar.setEditable(false);   
        }else{
                JOptionPane.showMessageDialog(rootPane,"La cuenta introducida no existe","Error",JOptionPane.ERROR_MESSAGE);
            }  
            
       
    }//GEN-LAST:event_ConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConsultarCuenta dialog = new ConsultarCuenta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Consultar;
    private javax.swing.JButton Limpiar;
    private javax.swing.JTextArea cuentaConsultada;
    private javax.swing.JTextField cuentaConsultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
