
import java.util.ArrayList;

/**
 *
 * @author CrisRodFe
 */
public class Listado extends javax.swing.JDialog {
        
        
        
        
    /**
     * Creates new form Listado
     * @param parent
     * @param modal
     */
    public Listado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
 //Cargamos los datos de las cuentas guardados en el archivo
        Serializar sr = new Serializar();
        String archivo = "datosClientes.dat";            
        ArrayList<CuentaBancaria> cuenta =(ArrayList<CuentaBancaria>)sr.leerObjeto(archivo);//Cargamos los datos del archivo en un array
        
        for(int i = 0;i<cuenta.size();i++){
           //Imprimimos por pantalla los datos de la cuenta introducida por teclado si existe.
          mostrar.append("DATOS DE LA CUENTA\n"+
                                   "NOMBRE: "+cuenta.get(i).getTitularCuenta().getNombre()+"\n"+
                                   "APELLIDOS: "+cuenta.get(i).getTitularCuenta().getApellidos()+"\n"+
                                   "FECHA DE NACIMIENTO: "+cuenta.get(i).getTitularCuenta().getFechaNacimiento()+"\n"+
                                   "TIPO DE CUENTA: "+cuenta.get(i).getClass().getName()+"\n"+
                                   "Nº DE CUENTA: "+cuenta.get(i).getNumeroCuenta()+"\n"+                                         
                                   "SALDO ACTUAL: "+cuenta.get(i).getSaldo()+"€"+
                                   "\n#######################################################\n\n");
           
        }                                        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listado = new javax.swing.JScrollPane();
        mostrar = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listado de cuentas");
        setModal(true);

        mostrar.setEditable(false);
        mostrar.setColumns(20);
        mostrar.setRows(5);
        listado.setViewportView(mostrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listado, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listado, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Listado dialog = new Listado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setLocationRelativeTo(null);
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane listado;
    private javax.swing.JTextArea mostrar;
    // End of variables declaration//GEN-END:variables
}
