
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author CrisRodFe
 */
public class Retirada extends javax.swing.JDialog {
    //Cargamos los datos de las cuentas guardados en el archivo
    Serializar sr = new Serializar();
    String archivo = "datosClientes.dat";            
    ArrayList<CuentaBancaria> cuenta =(ArrayList<CuentaBancaria>)sr.leerObjeto(archivo);
    ArrayList<CuentaCorrienteEmpresa>empresa=(ArrayList<CuentaCorrienteEmpresa>)sr.leerObjeto(archivo);
    /**
     * Creates new form Retirada
     * @param parent
     * @param modal
     */
    public Retirada(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cantidadRetirar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cuentaRetirar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nuevoSaldo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Retirar = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("RETIRAR DINERO");
        setAlwaysOnTop(true);
        setModal(true);

        jLabel2.setText("Cantidad");

        jLabel1.setText("Nº de Cuenta");

        nuevoSaldo.setEditable(false);

        jLabel4.setText("Nuevo saldo");

        jLabel3.setText("€");

        Retirar.setText("Retirar");
        Retirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetirarActionPerformed(evt);
            }
        });

        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });

        jLabel20.setText("€");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(cuentaRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(cantidadRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(nuevoSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel20))
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Retirar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Limpiar)
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuentaRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cantidadRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nuevoSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Retirar)
                    .addComponent(Limpiar)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Limpia las casillas del panel.
     * @param evt 
     */
    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        cantidadRetirar.setText("");
        cuentaRetirar.setText("");
        nuevoSaldo.setText("");
        
    }//GEN-LAST:event_LimpiarActionPerformed
    /**
     * Recoge una cantidad introducida por teclado y se resta al atributo saldo.
     * Se comprueba que el nº de cuenta exista y que el saldo se mayor que la cantidad.
     * @param evt 
     */
    private void RetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetirarActionPerformed
        boolean existe=false;
        int a = 0;
        //Recorremos los objetos guardados
        for(int i= 0;i<cuenta.size();i++){    
            //Si la cuenta introducida existe memorizamos su posición.
            if(cuenta.get(i).numeroCuenta.equals(cuentaRetirar.getText())){
                existe = true;
                a = i;
            }
        }    
            if(existe){                
                Float saldo = cuenta.get(a).getSaldo();//Obtenemos el saldo actual de la cuenta
                Float retirar = Float.parseFloat(cantidadRetirar.getText());//Cantidad introducida por teclado
                
                //Si la cuenta es de tipo empresa permitimos un descubierto determinado por el valor de la variable maxDesc
                if(cuenta.get(a).getClass().getName().equals("CuentaCorrienteEmpresa")){
                    if(empresa.get(a).getMaxDes()>(saldo-retirar)){
                        JOptionPane.showMessageDialog(rootPane,"No puede retirar la cantidad indicada.\nMáximo descubierto sobrepasado","Error",JOptionPane.ERROR_MESSAGE);
                    }else{
                        empresa.get(a).setSaldo(saldo-retirar);
                        sr.grabarObjeto(empresa, archivo);
                        nuevoSaldo.setText(String.valueOf(empresa.get(a).getSaldo()));
                        cuentaRetirar.setEditable(false);
                        cantidadRetirar.setEditable(false);
                        nuevoSaldo.setEditable(false);
                    }
                }else{
                //Si la cuenta no es de tipo corriente de empresa comprobamos que el saldo sea mayor que la cantidad a retirar.    
                    if(saldo>retirar){
                        cuenta.get(a).setSaldo(saldo-retirar);
                        sr.grabarObjeto(cuenta, archivo);
                        nuevoSaldo.setText(String.valueOf(cuenta.get(a).getSaldo()));
                        cuentaRetirar.setEditable(false);
                        cantidadRetirar.setEditable(false);
                        nuevoSaldo.setEditable(false);
                    }else{
                        JOptionPane.showMessageDialog(rootPane,"No tiene suficiente saldo","Error",JOptionPane.ERROR_MESSAGE);}
                    }
                
            } else{
                JOptionPane.showMessageDialog(rootPane,"La cuenta introducida no existe","Error",JOptionPane.ERROR_MESSAGE);
        }
            
    }//GEN-LAST:event_RetirarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Retirada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Retirada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Retirada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Retirada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Retirada dialog = new Retirada(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setLocationRelativeTo(null);
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Limpiar;
    private javax.swing.JButton Retirar;
    private javax.swing.JTextField cantidadRetirar;
    private javax.swing.JTextField cuentaRetirar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nuevoSaldo;
    // End of variables declaration//GEN-END:variables
}
